# Generated by Django 4.2 on 2023-10-11 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exist.'}, help_text='Required 30 characters or fewer starting with a letter, Letters, digits', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_\\.]+$', 'Enter a valid sure name starting with a-z.', 'invalid')], verbose_name='username'),
        ),
    ]
